### ISSUE TITLE
Clicking on Submenu disables it

### ISSUE THREAD

**Issue by wilsonk** [david-vanderson/gui#20]
Not sure if this is an actual bug or expected behavior, but if you open the sdl-test binary and click on OpenDemoWindow, then drop down the Menus, then hover over the File menu, then left click on the 'submenu' option. The submenu disappears and won't popup again until you click on 'submenue' again or leave the File popup area and re-enter it again, or click on 'submenu' again.

Again, I am not sure if this is intended behavior or not. Just seemed a little off to me, so I thought I would open an issue, just in case it is a bug.

**Comment by david-vanderson** [comment]
That is the current intended behavior, but not the best.  I should go over it again.  Thanks!

**Comment by david-vanderson** [comment]
I've committed a fix for this - does it solve the issue for you?

**Comment by wilsonk** [comment]
Yes, this solved the issues for me. Works great now.
