### ISSUE TITLE
[Compilation]: Error compiling zig-libxml2 using zig 0.10.1 

### ISSUE THREAD

**Issue by Elkantor** [david-vanderson/gui#6]
Hi,

When trying to compile the sdl standalone test program, using zig build sdl-test, I got this error:
![image](https://user-images.githubusercontent.com/20202017/222760242-a1e848db-9e43-481c-b0f0-ff747c9c14ea.png)

Do you know if it comes from the zig version of the compiler (0.10.1), or from the external dependency (zig-libxml2)?

**Comment by alichraghi** [comment]
you're using an old compiler version. use nightly/master builds

**Comment by david-vanderson** [comment]
Thank you for the report!  @alichraghi is right, and also the zig build system and dependencies are going through a major overhaul right now.  If you can wait that's likely the best option.  Otherwise you'll have to update to zig master and then I'll help get you up and running.

**Comment by david-vanderson** [comment]
Please open a new issue if needed.
